language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
        - php: 5.6
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: 7.0
        - php: hhvm

before_install:
  - composer self-update

install:
  # --prefer-source to pass GitHub limits (see https://twitter.com/travisci/status/297761892775100418 for example).
  - composer install --no-interaction --prefer-source

script:
  - ./bin/phpspec run -f pretty -v
